- SQL: |
      TRUNCATE TABLE `fisia-data-lake.refined.fis_ref_tab_flt_login_nike_unite`;
      INSERT INTO fisia-data-lake.refined.fis_ref_tab_flt_login_nike_unite(cod_token, nom_email_cliente, cod_cpf_cnpj_cliente, num_tipo_cliente, dat_ultimo_login, cod_sexo, dat_evento, cod_ip_origem, cod_canal, cod_status, dat_chave)
      SELECT
          token as cod_token,
          email as nom_email_cliente,
          cpf_cnpj as cod_cpf_cnpj_cliente,
          tipo_cliente as num_tipo_cliente,
          dt_ultimo_login as dat_ultimo_login,
          sexo as cod_sexo,
          DATETIME(dt_evento, "America/Sao_Paulo") as dat_evento,
          ip as cod_ip_origem,
          canal as cod_canal,
          status as cod_status,
          dat_chave
      FROM `fisia-data-lake.trusted.fis_trd_gcs_6000_kfk_login_nike_unite`
  ACTIVE: "1"
