- SQL: |
      create temp table temp_nps as (
         select
            cast(parse_date('%m/%e/%Y', substring(if(length(split(data_resposta,'/')[safe_offset(0)]) = 1, 0||data_resposta, data_resposta), 1, 10)) as date) as dat_resposta_nps
          , cast(parse_date('%m/%e/%Y', substring(if(length(split(data_envio,'/')[safe_offset(0)]) = 1, 0||data_envio, data_envio), 1, 10)) as date) as dat_envio_nps
          , date_diff(parse_date('%m/%e/%Y', substring(if(length(split(data_resposta,'/')[safe_offset(0)]) = 1, 0||data_resposta, data_resposta), 1, 10)), parse_date('%m/%e/%Y', substring(if(length(split(data_envio,'/')[safe_offset(0)]) = 1, 0||data_envio, data_envio), 1, 10)), day) as num_dias_resposta
          , cast(jobid as int64) as cod_job
          , pedido as cod_pedido
          , cast(nps as int64) as num_nota_nps
          , if(length(trim(resposta)) > 0, resposta, null) as des_resposta_nps
          , IF(detrator_entrega = '1' and d_nps.des_classificacao_nps = 'DETRATOR', 'SIM', 'NAO') as flg_detrator_entrega
          , IF(detrator_qualidade = '1' and d_nps.des_classificacao_nps = 'DETRATOR', 'SIM', 'NAO') as flg_detrator_qualidade
          , IF(detrator_troca = '1' and d_nps.des_classificacao_nps = 'DETRATOR', 'SIM', 'NAO') as flg_detrator_troca
          , IF(detrator_atendimento = '1' and d_nps.des_classificacao_nps = 'DETRATOR', 'SIM', 'NAO') as flg_detrator_atendimento
          , IF(detrator_produtoerrado = '1' and d_nps.des_classificacao_nps = 'DETRATOR', 'SIM', 'NAO') as flg_detrator_produto_errado
          , IF(detrator_produtodefeito = '1' and d_nps.des_classificacao_nps = 'DETRATOR', 'SIM', 'NAO') as flg_detrator_produto_avariado
          , IF(neutro_qualidadeatendimento = '1' and d_nps.des_classificacao_nps = 'NEUTRO', 'SIM', 'NAO') as flg_neutro_qualidade_atendimento
          , IF(neutro_entregarapida = '1' and d_nps.des_classificacao_nps = 'NEUTRO', 'SIM', 'NAO') as flg_neutro_entrega_rapida
          , IF(neutro_qualidadeproduto = '1' and d_nps.des_classificacao_nps = 'NEUTRO', 'SIM', 'NAO') as flg_neutro_qualidade_produto
          , IF(neutro_prazolongo = '1' and d_nps.des_classificacao_nps = 'NEUTRO', 'SIM', 'NAO') as flg_neutro_prazo_longo
          , IF(neutro_atrasoentrega = '1' and d_nps.des_classificacao_nps = 'NEUTRO', 'SIM', 'NAO') as flg_neutro_atraso_entrega
          , IF(neutro_usabilidadesite = '1' and d_nps.des_classificacao_nps = 'NEUTRO', 'SIM', 'NAO') as flg_neutro_usabilidade_site
          , IF(promotor_atendimentoloja = '1' and d_nps.des_classificacao_nps = 'PROMOTOR', 'SIM', 'NAO') as flg_promotor_atendimento_loja
          , IF(promotor_entregarapida = '1' and d_nps.des_classificacao_nps = 'PROMOTOR', 'SIM', 'NAO') as flg_promotor_entrega_rapida
          , IF(promotor_usabilidadesite = '1' and d_nps.des_classificacao_nps = 'PROMOTOR', 'SIM', 'NAO') as flg_promotor_usabilidade_site
          , IF(promotor_atendimentosac = '1' and d_nps.des_classificacao_nps = 'PROMOTOR', 'SIM', 'NAO') as flg_promotor_atendimento_sac
          , IF(promotor_qualidadeproduto = '1' and d_nps.des_classificacao_nps = 'PROMOTOR', 'SIM', 'NAO') as flg_promotor_qualidade_produto
          , IF(promotor_confiancamarca = '1' and d_nps.des_classificacao_nps = 'PROMOTOR', 'SIM', 'NAO') as flg_promotor_confianca_marca
        from `{PROJECT}.{CAMADA_ORIGEM}.fis_trd_api_6000_salesforce_nps` n
        join `{PROJECT}.{CAMADA}.fis_ref_gld_dim_classificacao_nota_nps` d_nps
          on cast(n.nps as int64) = d_nps.num_nota_nps
        where dat_chave between date_sub(current_date('America/Sao_Paulo'), interval 7 day) and current_date('America/Sao_Paulo')
      );

      MERGE INTO `{PROJECT}.{CAMADA}.fis_ref_gld_fat_nps_digital_1p` ref_nps
      USING temp_nps t_nps
        ON ref_nps.cod_pedido = t_nps.cod_pedido
      WHEN MATCHED and ref_nps.num_nota_nps <> t_nps.num_nota_nps
        THEN UPDATE SET
            ref_nps.dat_resposta_nps = t_nps.dat_resposta_nps
          , ref_nps.dat_envio_nps = t_nps.dat_envio_nps
          , ref_nps.num_dias_resposta = t_nps.num_dias_resposta
          , ref_nps.cod_job = t_nps.cod_job
          , ref_nps.num_nota_nps = t_nps.num_nota_nps
          , ref_nps.des_resposta_nps = t_nps.des_resposta_nps
          , ref_nps.flg_detrator_entrega = t_nps.flg_detrator_entrega
          , ref_nps.flg_detrator_qualidade = t_nps.flg_detrator_qualidade
          , ref_nps.flg_detrator_troca = t_nps.flg_detrator_troca
          , ref_nps.flg_detrator_atendimento = t_nps.flg_detrator_atendimento
          , ref_nps.flg_detrator_produto_errado = t_nps.flg_detrator_produto_errado
          , ref_nps.flg_detrator_produto_avariado = t_nps.flg_detrator_produto_avariado
          , ref_nps.flg_neutro_qualidade_atendimento = t_nps.flg_neutro_qualidade_atendimento
          , ref_nps.flg_neutro_entrega_rapida = t_nps.flg_neutro_entrega_rapida
          , ref_nps.flg_neutro_qualidade_produto = t_nps.flg_neutro_qualidade_produto
          , ref_nps.flg_neutro_prazo_longo = t_nps.flg_neutro_prazo_longo
          , ref_nps.flg_neutro_atraso_entrega = t_nps.flg_neutro_atraso_entrega
          , ref_nps.flg_neutro_usabilidade_site = t_nps.flg_neutro_usabilidade_site
          , ref_nps.flg_promotor_atendimento_loja = t_nps.flg_promotor_atendimento_loja
          , ref_nps.flg_promotor_entrega_rapida = t_nps.flg_promotor_entrega_rapida
          , ref_nps.flg_promotor_usabilidade_site = t_nps.flg_promotor_usabilidade_site
          , ref_nps.flg_promotor_atendimento_sac = t_nps.flg_promotor_atendimento_sac
          , ref_nps.flg_promotor_qualidade_produto = t_nps.flg_promotor_qualidade_produto
          , ref_nps.flg_promotor_confianca_marca = t_nps.flg_promotor_confianca_marca
      WHEN NOT MATCHED
        THEN INSERT(dat_resposta_nps, dat_envio_nps, num_dias_resposta, cod_job, cod_pedido, num_nota_nps, des_resposta_nps, flg_detrator_entrega, flg_detrator_qualidade, flg_detrator_troca, flg_detrator_atendimento, flg_detrator_produto_errado, flg_detrator_produto_avariado, flg_neutro_qualidade_atendimento, flg_neutro_entrega_rapida, flg_neutro_qualidade_produto, flg_neutro_prazo_longo, flg_neutro_atraso_entrega, flg_neutro_usabilidade_site, flg_promotor_atendimento_loja, flg_promotor_entrega_rapida, flg_promotor_usabilidade_site, flg_promotor_atendimento_sac, flg_promotor_qualidade_produto, flg_promotor_confianca_marca)
          VALUES(t_nps.dat_resposta_nps, t_nps.dat_envio_nps, t_nps.num_dias_resposta, t_nps.cod_job, t_nps.cod_pedido, t_nps.num_nota_nps, t_nps.des_resposta_nps, t_nps.flg_detrator_entrega, t_nps.flg_detrator_qualidade, t_nps.flg_detrator_troca, t_nps.flg_detrator_atendimento, t_nps.flg_detrator_produto_errado, t_nps.flg_detrator_produto_avariado, t_nps.flg_neutro_qualidade_atendimento, t_nps.flg_neutro_entrega_rapida, t_nps.flg_neutro_qualidade_produto, t_nps.flg_neutro_prazo_longo, t_nps.flg_neutro_atraso_entrega, t_nps.flg_neutro_usabilidade_site, t_nps.flg_promotor_atendimento_loja, t_nps.flg_promotor_entrega_rapida, t_nps.flg_promotor_usabilidade_site, t_nps.flg_promotor_atendimento_sac, t_nps.flg_promotor_qualidade_produto, t_nps.flg_promotor_confianca_marca)
  ACTIVE: "1"
