name: Deploy DAGs to Composer
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  deploy:
    name: Upload DAG files to Airflow
    runs-on: ubuntu-latest
    steps:
      # copying files to machine
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # checking changed files
      - name: Check changed files
        id: changed-files
        uses: tj-actions/changed-files@v34.5.0
        with:
          files: |
            dags/**
      # listing changed files
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed."
          done
      # checking deleted files
      - name: List all deleted files
        if: steps.changed-files.outputs.any_deleted == 'true'
        run: |
          all_files=""
          for file in ${{ steps.changed-files.outputs.deleted_files }}; do
            if
          done
      #pushing files to airflow composer
      - name: Push files to composer
        if: steps.changed-files.outputs.any_modified == 'true'
        run: |
          BRANCH=$(echo ${{ github.ref }} | sed 's/refs\/heads\///g')

          BUCKET_PATH=${{ secrets.DEV_AIRFLOW_BUCKET_2_3_4 }}/dags/data_eng_fis_cliente/

          echo "Moving files to '$BUCKET_PATH'"

          echo '
          argo submit -n argo -w deploy/deploy-data-gcp.yml \
            --parameter "file_changed=${{ steps.changed-files.outputs.all_changed_files }}" \
            --parameter "file_deleted=${{ steps.changed-files.outputs.deleted_files }}" \
            --parameter "file_renamed=${{ steps.changed-files.outputs.renamed_files }}" \
            --parameter "bucket_path=$BUCKET_PATH" \
            --parameter "branch=$BRANCH"
          '
